# -*- coding: utf-8 -*-
"""First_Colab_File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x4N8lgMhKhaiH20mOKm_lLgHURoAZu2V
"""

a=10
b=5

resulta = a/b

a=2
b=6

a*b

"""# Matrix (Array) : Array is a Data Type (array ma3neha tableau saghroun)"""

# Commentaire
matrix = [[1,2,3],   # size = 3x3  # Initialisation d'une VARIABLE de type 'array'
          [4,5,6],    # matrix or array is defined by '[[ ]]'
          [7,8,9]]

print("Voila ma Matrice : " , matrix)    # affichage de la variable

import numpy as np  # numpy : bibliotheque des statistics & les matrices (arrays) # np : alias ou abbréviation

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

mean_value = np.mean(matrix)
print("La Moyenne est égale à : " , mean_value)

median_value = np.median(matrix)
print("La Médiane est égale à : " , median_value)

matrix_2 = np.array([[0, 3, 6],
                     [9, 12, 15]])

matrix_2

"""# List"""

lista = [-2.5, 99, 0, 10.5, 2024]
lista

max(lista)

min(lista)

sum(lista)

#index : indice  # l'indexation en python débute de 0 pas de 1
lista[0]

lista_alphabet = ['a', 'b', 'c', 'd', 'e', 'a']
lista_alphabet

lista_alphabet.append('f') # l'ajout d'un élément
lista_alphabet

lista_alphabet.count('a') # compte le nombre d'éléments









!git init

!git add /content/drive/MyDrive/First_Colab_File.ipynb

!git commit -m "Initial commit"

!git config --global user.email "you@example.com"
!git config --global user.name "Your Name"

!git commit -m "Initial commit"

import scipy

!git push main







